In [53]:
import pandas as pd

In [54]:
df = pd.read_csv('BlinkIT-Grocery-Data.csv')

In [55]:
df.columns

Index(['Item Fat Content', 'Item Identifier', 'Item Type',
       'Outlet Establishment Year', 'Outlet Identifier',
       'Outlet Location Type', 'Outlet Size', 'Outlet Type', 'Item Visibility',
       'Item Weight', 'Sales', 'Rating'],
      dtype='str')

In [56]:
df.shape

(8523, 12)

In [57]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Fat Content           8523 non-null   str
 1   Item Identifier            8523 non-null   str
 2   Item Type                  8523 non-null   str
 3   Outlet Establishment Year  8523 non-null   int64
 4   Outlet Identifier          8523 non-null   str
 5   Outlet Location Type       8523 non-null   str
 6   Outlet Size                8523 non-null   str
 7   Outlet Type                8523 non-null   str
 8   Item Visibility            8523 non-null   float64
 9   Item Weight                7060 non-null   float64
 10  Sales                      8523 non-null   float64
 11  Rating                     8523 non-null   float64
dtypes: float64(4), int64(1), str(7)
memory usage: 1.2 MB
None

In [58]:
print(df.head())

  Item Fat Content Item Identifier              Item Type  \
0          Regular           FDX32  Fruits and Vegetables
1          Low Fat           NCB42     Health and Hygiene
2          Regular           FDR28           Frozen Foods
3          Regular           FDL50                 Canned
4          Low Fat           DRI25            Soft Drinks

   Outlet Establishment Year Outlet Identifier Outlet Location Type  \
0                       2012            OUT049               Tier 1
1                       2022            OUT018               Tier 3
2                       2016            OUT046               Tier 1
3                       2014            OUT013               Tier 3
4                       2015            OUT045               Tier 2

  Outlet Size        Outlet Type  Item Visibility  Item Weight     Sales  \
0      Medium  Supermarket Type1         0.100014        15.10  145.4786
1      Medium  Supermarket Type2         0.008596        11.80  115.3492
2       Small  Supermarket Type1         0.025896        13.85  165.0210
3        High  Supermarket Type1         0.042278        12.15  126.5046
4       Small  Supermarket Type1         0.033970        19.60   55.1614

   Rating
0     5.0
1     5.0
2     5.0
3     5.0
4     5.0

In [59]:
#checking for n
print(df.isnull().sum())

Item Fat Content                0
Item Identifier                 0
Item Type                       0
Outlet Establishment Year       0
Outlet Identifier               0
Outlet Location Type            0
Outlet Size                     0
Outlet Type                     0
Item Visibility                 0
Item Weight                  1463
Sales                           0
Rating                          0
dtype: int64

In [17]:
df['Item Weight'] = df['Item Weight'].fillna(df['Item Weight'].median())

In [20]:
# Standardize fat content
df['Item Fat Content'] = df['Item Fat Content'].replace({
    'LF': 'Low Fat',
    'low fat': 'Low Fat',
    'reg': 'Regular'
})

In [21]:
df['Item Fat Content'].unique()

<ArrowStringArray>
['Regular', 'Low Fat']
Length: 2, dtype: str

In [22]:
df.describe()

,Outlet Establishment Year,Item Visibility,Item Weight,Sales,Rating
count,8523.000000,8523.000000,8523.00000,8523.000000,8523.000000
mean,2016.450546,0.066132,12.81342,140.992783,3.965857
std,3.189396,0.051598,4.22724,62.275067,0.605651
min,2011.000000,0.000000,4.55500,31.290000,1.000000
25%,2014.000000,0.026989,9.31000,93.826500,4.000000
50%,2016.000000,0.053931,12.60000,143.012800,4.000000
75%,2018.000000,0.094585,16.00000,185.643700,4.200000
max,2022.000000,0.328391,21.35000,266.888400,5.000000

In [28]:
#Category generating more revenue
category_sales = (
    df.groupby('Item Type')['Sales']
      .sum()
      .sort_values(ascending=False)
)

category_sales.head(10)

Item Type
Fruits and Vegetables    178124.0810
Snack Foods              175433.9224
Household                135976.5254
Frozen Foods             118558.8814
Dairy                    101276.4616
Canned                    90706.7290
Baking Goods              81894.7364
Health and Hygiene        68025.8388
Meat                      59449.8638
Soft Drinks               58514.1670
Name: Sales, dtype: float64

In [29]:
#outlet types generate the most revenue
outlet_sales = (
    df.groupby('Outlet Type')['Sales']
      .sum()
      .sort_values(ascending=False)
)

outlet_sales

Outlet Type
Supermarket Type1    787549.8928
Grocery Store        151939.1490
Supermarket Type2    131477.7764
Supermarket Type3    130714.6746
Name: Sales, dtype: float64

In [30]:
#location tier performance
location_sales = (
    df.groupby('Outlet Location Type')['Sales']
      .sum()
      .sort_values(ascending=False)
)

location_sales

Outlet Location Type
Tier 3    472133.0332
Tier 2    393150.6476
Tier 1    336397.8120
Name: Sales, dtype: float64

In [31]:
#higher-rated products generate more sales
df[['Sales','Rating']].corr()n  l

           Sales    Rating
Sales   1.000000  0.011329
Rating  0.011329  1.000000

In [32]:
#Does visibility affect sales
df[['Sales','Item Visibility']].corr()

                    Sales  Item Visibility
Sales            1.000000        -0.001315
Item Visibility -0.001315         1.000000

In [34]:
#sales by outlet size
df.groupby('Outlet Size')['Sales'].sum().sort_values(ascending=False)

Outlet Size
Medium    507895.7364
Small     444794.1704
High      248991.5860
Name: Sales, dtype: float64

In [35]:
#sales by fat content
df.groupby('Item Fat Content')['Sales'].sum().sort_values(ascending=False)

Item Fat Content
Low Fat    776319.6884
Regular    425361.8044
Name: Sales, dtype: float64

In [36]:
#top 10 rated category
df.groupby('Item Type')['Rating'].mean().sort_values(ascending=False).head(10)

Item Type
Meat                     4.023059
Household                3.998681
Canned                   3.994299
Health and Hygiene       3.986154
Baking Goods             3.983025
Frozen Foods             3.971145
Dairy                    3.965836
Seafood                  3.959375
Fruits and Vegetables    3.956169
Others                   3.954438
Name: Rating, dtype: float64

In [51]:
df.to_excel("cleaned_retail_data.xlsx", index=False)